import express, { Application, Request, Response } from "express";
import http from "http";
import { Server, Socket } from "socket.io";
import Docker from "dockerode";
import cors from "cors";
import path from "path";
import fs from "fs";

const app: Application = express();
app.use(cors());
app.use(express.json());

const server = http.createServer(app);
const io = new Server(server, {
  cors: { origin: "*", methods: ["GET", "POST"] }
});

const docker = new Docker(); // Automatically connects to your running Docker Desktop
const WORKSPACE_DIR = path.resolve("./workspace");

// Ensure workspace directory exists
if (!fs.existsSync(WORKSPACE_DIR)) {
  fs.mkdirSync(WORKSPACE_DIR, { recursive: true });
}

// 1. Endpoint to receive and write code files generated by your frontend/LLM
app.post("/api/save-files", (req: Request, res: Response) => {
  try {
    const { files } = req.body; // Expects an array: [{ path: "src/App.tsx", content: "..." }]
    if (!Array.isArray(files)) {
      return res.status(400).json({ error: "Invalid files format" });
    }

    files.forEach((file) => {
      const fullPath = path.join(WORKSPACE_DIR, file.path);
      const dirName = path.dirname(fullPath);
      
      if (!fs.existsSync(dirName)) {
        fs.mkdirSync(dirName, { recursive: true });
      }
      fs.writeFileSync(fullPath, file.content, "utf-8");
    });

    res.json({ success: true, message: "Files written to Docker workspace" });
  } catch (err: any) {
    console.error("Error writing files:", err);
    res.status(500).json({ error: err.message });
  }
});

// 2. WebSocket handler to spawn and stream a Docker container terminal
io.on("connection", async (socket: Socket) => {
  console.log(`Client connected: ${socket.id}`);
  let container: Docker.Container | null = null;

  try {
    // Pull or use node:18-alpine, create container, map workspace folder, and expose port 3000
    container = await docker.createContainer({
      Image: "node:18-alpine",
      Cmd: ["sh"],
      Tty: true,
      OpenStdin: true,
      StdinOnce: false,
      WorkingDir: "/app",
      HostConfig: {
        Binds: [`${WORKSPACE_DIR}:/app`],
        PortBindings: {
          "3000/tcp": [{ HostPort: "3000" }]
        }
      },
      ExposedPorts: {
        "3000/tcp": {}
      }
    });

    await container.start();
    console.log(`Docker container started: ${container.id.substring(0, 12)}`);

    const execStream = await container.attach({
      stream: true,
      stdout: true,
      stderr: true,
      stdin: true
    });

    // Stream container shell output to frontend Xterm terminal
    execStream.on("data", (chunk: Buffer) => {
      socket.emit("terminal:output", chunk.toString());
    });

    // Receive keystrokes/commands from frontend terminal and pass to container
    socket.on("terminal:input", (input: string) => {
      execStream.write(input);
    });

    // Destroy container when user closes session or disconnects
    socket.on("disconnect", async () => {
      if (container) {
        try {
          await container.stop();
          await container.remove();
          console.log("Container stopped and cleaned up.");
        } catch (e) {
          console.error("Cleanup error:", e);
        }
      }
    });

  } catch (err: any) {
    console.error("Docker container error:", err);
    socket.emit("terminal:output", "\r\n[Error]: Failed to start Docker container. Ensure Docker Desktop is running.\r\n");
  }
});

const PORT = process.env.PORT || 4001;
server.listen(PORT, () => {
  console.log(`🚀 Docker Terminal backend running on http://localhost:${PORT}`);
});